#!/usr/bin/env ruby
require 'optparse'
require_relative 'remix'

options = {:output => $stdout}
OptionParser.new do |opts|
  opts.banner = "Usage: filtergoogle [options] [FILES]"

  opts.on("-o", "--output FILENAME", "Send output to filename") do |filename|
    options[:output] = File.open(filename, "w")
  end
end.parse!

if ARGV.size > 0
# Use files as input
  ARGV.each do |filename|
    File.open(filename) do |file|
      Remix.filter_google_watermark(file, options[:output])
    end
  end
else
# Use stdin as input
  Remix.filter_google_watermark($stdin, options[:output])
end
